import uuid
from datetime import datetime
from enum import Enum

from sqlalchemy import Boolean, Enum as SAEnum, Float, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.agency import Agency
from app.models.base import Base
from app.utils import generate_uuid


class PopularQuestionSource(str, Enum):
    seed = "seed"
    auto = "auto"
    manual = "manual"


class PopularQuestion(Base):
    """A frequently-asked citizen question surfaced on the public chat landing page.

    ``source="auto"`` rows are (re)generated by the scheduled ``regenerate`` job;
    editing one flips it to ``manual`` so it survives future churn. A hidden row
    acts as a tombstone: its ``text_key`` blocks the same question from being
    regenerated.
    """

    __tablename__ = "popular_questions"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=generate_uuid)
    text: Mapped[str] = mapped_column(Text)
    text_key: Mapped[str] = mapped_column(String(500), unique=True)
    agency_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("agencies.id", ondelete="SET NULL"), nullable=True,
    )
    agency: Mapped["Agency | None"] = relationship(lazy="raise")
    source: Mapped[PopularQuestionSource] = mapped_column(
        SAEnum(PopularQuestionSource, native_enum=False, create_constraint=False, length=10),
        default=PopularQuestionSource.manual,
    )
    pinned: Mapped[bool] = mapped_column(Boolean, default=False)
    hidden: Mapped[bool] = mapped_column(Boolean, default=False)
    sort_order: Mapped[int] = mapped_column(Integer, default=0)
    score: Mapped[float | None] = mapped_column(Float, nullable=True)

    created_at: Mapped[datetime] = mapped_column(server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(server_default=func.now(), onupdate=func.now())

    def __str__(self) -> str:
        return self.text[:60]
