from tortoise import BaseDBAsyncClient

RUN_IN_TRANSACTION = True

# NOTE: MODELS_STATE below is carried over from migration 28 as a placeholder.
# It must be regenerated by running `aerich migrate` in an environment with a
# live database (it is a machine-generated snapshot, not hand-authorable). The
# upgrade/downgrade DDL here is correct and applies the domain_events outbox
# table on `aerich upgrade`.


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE TABLE IF NOT EXISTS "domain_events" (
            "id" UUID NOT NULL PRIMARY KEY,
            "event_type" VARCHAR(100) NOT NULL,
            "payload" JSONB NOT NULL DEFAULT '{}'::jsonb,
            "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            "dispatched_at" TIMESTAMPTZ
        );
        CREATE INDEX IF NOT EXISTS "idx_domain_events_undispatched"
            ON "domain_events" ("dispatched_at", "created_at");"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        DROP TABLE IF EXISTS "domain_events";"""


MODELS_STATE = (
    "eJztXWtT6zYa/iuefGpnKAs5QLvsZSZw0m62cGA5sNtp0zGKrRAV23JlOUA757+vJMeOL7"
    "KJkjixE82c4YCtx5dH8qv3Kv3ZcbENneCw9wQ9661zbvzZ8YAL2S+5MwdGB/j+/Dg/QMHI"
    "EU0Bb4OgOAhGASXAouz4GDgBZIdsGFgE+RRhj7f+AU8h8VzoUUMA3wxxyUOOtrHF4Mh7qm"
    "o49K4RIZgEBp1A4zG++6MhHsgYE+yKM5igJ+QBx/gc+mAEAmgE1gS6QNwp9NDvITQpfoKs"
    "LWH3++VXdhh5NnxlbzL70382xwg6doYZZPMLiOMmffPFsYeHwcfvRUv+FiPTwk7oevPW/h"
    "udYC9pHobIPuQYfo49PySAQjvFmRc6zoze+FD0xOwAJSFMHtWeH7DhGIQOZ77z93HoWZxw"
    "g/XaYUgR68n4Nia/+T87hY7ht8x1weyQhT3eqcijnJg/v0SvOCdAHO3w+17+q3f31Yezr8"
    "Ur44A+EXFS0NP5IoCAgggqSJ6zKv4v8Ho5AUTOa9w+xyx70GU4jQ/MSZ2P3pjVmKDlWOu4"
    "4NV0oPdEJ+zP7ulpBY3/7d0JJlkrQSVmX1T0qX2anepG5zilcwqDCSbUVCUyi1qKztkA3B"
    "qbp0cLkHl6VMolP5Wl0sFPWIXEuH0r6atlMKafrEDkPXylciJzsJbwWUHfff+ne/7MbhD8"
    "7qRZ++q695Mg1H2bnbm6+fRD3DzF8uXVzUWOXHZ7DwoBH1EjHal9L3QFyQP2rMCzYIFsyW"
    "U2J047vdtBcRbqXF/enhvsx9Bj588N9oP91u2x37q9vIqwyOA+XkQ2HJfLhuOCbGBk0jBY"
    "lvM5eoNUM4UMTaGEbZuAMT03xH9DL2p2bkT/Dz2Xcwo9/h7nRuqPoWejgD+QzaCz35bpm+"
    "4ifdMt75tuoW9ASLGZetJiL11g7EDgyaWPDJ7rphHD19VPco15HVLo4ubmKiOFLgZ5MfNw"
    "fdFnX4IgmzVCVBwefLqXDP/AZIodpCagRYI/MlIocmGJtlFA5/i1Z/DD+JfWCfzBdf/zfe"
    "/6NsP3x959n5/pZiR+fPSrs9wYTy5i/G9w/y+D/2n8fPOpn1esk3b3P3f4M4kB7OEXE9jp"
    "144Px4eyMzVXyQMLy+aRf3+++VQyUWdQuU588Bifv9jIogeGgwL6a22SbW7pjELkUOQFh/"
    "yGNdk3nI7qyTw/b+f6i1+gOJk7mKgomwmgJdpR3co69Gwfs5uZIXFUeMzjWknn8dHRYhrO"
    "UZWOcySbSSemCxkjEndHOac5WCspXf8IFaxMILCh0oeeg7WSzONFh2fV6Mzzyb15pg/YDR"
    "TYzIBayWUthjrwkfkM35T9RnlcKxmtZXQSyF4moOYYE1emIZdzWkS2ktUaBCgbbPF0LTG9"
    "y9XUAlBrqstrquyUz54AmlEgRaUfJFDdE8v3BB/WgQ8tk4AXFfdqHtcS8bJp/yp8ZRyx92"
    "fqwpuDgUQDLh/pMuwahnqjSK9tTEfKrrKET8G2RPUuCBWfIEwQfSuyP/BK5EkakmOevUUj"
    "hzV7IvbfN93jk29PvvtwdvIdayIeJTnybQXxRX8owSGFxJzM3ndRSZyDbTAYUM+IrEUO2y"
    "hgBps1MbkjmBFmSiRD6diUg/d0lLqWb1KMHWUzrwBsicqwAcuZ3VEYap4FTQJ9TCQCoHze"
    "kqO1prDAREUxBY5pAcdRkQc51FKCYCmJe9QcMcBejd3ODH0F3jKYfWbNxi+SXJb3eItRe8"
    "mcRSB/uSUCxVnkGoLE28j5Y+9g33jO20wqtyRqPJtAKoPGoW8v2bFZpO7YrXaseHie6Tx+"
    "TmXl8gMjYD2/AGKbmTPSFDQHP0nm4YvZBb7/8Q46oCShb5Zlfplc7Ao/NVnFmR+d9/ycky"
    "fs2NAzhQ+fXX9FUn4QV/vP7GLN/BAWosXHfugAsi5ebqPLKRDToOHCPy3cxWUfW/GU23Xz"
    "R4AHnsRT83vzO8W1GqGNKP+AZHUc8bmDykoO3ir5nt+t5SinQ5dX1GFMrVBewboRE1ON2z"
    "RmBYYbZY++S2GeMugCpJRVlINpd0mKT2kxQCWVq9QBbEMxrDkOjke/MT2pIulfTmQO1sox"
    "+WERMj+Uk/mhjEyZUHyXSqlUbAeRZycLEHl2UkokP5Wv9aFSIVmRPZwgtMPz4H2Hp3aj7I"
    "S1HblRFMztOq2FrM0tMRkKRnm53SBxBmjjYaeMhxZobh0KA7oCd3XrbgsVbZbGCrdXqLlW"
    "w2LtFX9V1ZjlJWibrsBsNocOe1vPejNdlXBqFrSX0a0yvbeqvL1E79UJP1rR3TVFV1YTMc"
    "K2JL+wIk0uh9uYxd2mryZJrldnNwfU9ErodWEQMBtK0XueRe2j/zwIEF8Eg5rLEViG30cq"
    "xfpnqvylQXtCWsG3kuewSOD3mED05P0I3wSN6YVb5PHn+ZJ4TSWuEHY+4NloL4m/JDs02B"
    "uy94LReh+Xvc+XvY/9zpetOaWmkARg9uIyn9T8/ME7Lqmk5YIrEzKTkRppnDEMu0fHJ4ab"
    "Xm8wc2G1RQczyxvWfjftRmuYG40i6ii5fRLABo3FYXgEu4D/PP6r+Pnt/PcPXf7z5INoMx"
    "I/j8WR79bodlvM71bleCv4N3wCpwgqFUqmIC0J8m1aK06v+rpo2C+N0eW/y8cD2+H07ASh"
    "ZTHVfW3CYf2ez9iysHAoK98rdX4WcHvp/0zcB7FLbdHRWAC2RMbWvpLVK4WE6XNmwMYXj/"
    "ao5aaUwFtJbi0rs7iQAq6eqcxZaUyT5ix+2zbNWZGNuYxrP4vU60Vueb1IHaPZ0RiNruna"
    "iY4t1N+EAVRN/U9BtOeYk7EGv/HD7DJNJe1dr3FqUGR8xp/798anh6urKqdxweRasQjsOr"
    "pKM0XJVqq/+lPg3MEgev6C4zx19qDKbQ5ZO748N2uo0zh3zP8cWExkSQSZg0GJmyNB5Mgd"
    "c0ijvz0ZdR9vHi6u+sbtXf9y8HkwM3GSeVqc5Ifmi9/f9XtXea+nF7zIZoOKJfcShE75kv"
    "mRfwvtJ74CDgjUdorJ4zS7OqFuZ3X6orGWW2tAUb+Xo9c5hbZU188Rswa1v83LOOQtAPmw"
    "aVICSf8VWiHfveiCIDjuyDThbItqbThua454Y60R75hGzG5Codq6nSmI1jhkGkdLYtP4eQ"
    "VOc6Gqs0UiVXldIRWoOsvHqZI3XkJvy2O15tYAza0hNb85XUQyOxa1lfLZUbbclZ4dd2d2"
    "LFeCy6fHNKYt5ZWbniGTHQIo9pGllEAngTYpJ6FteXTaO7JDc2xjCmaaJcLaVDHTYNfHSi"
    "UzmZTJOLS2fPAzG8xrD6e1xj+vHPeW4CmyhepYUGzTpyu1WsdxTX/WUqu0O6bSqu5+sdKm"
    "F0tw2uz0ZLGDpuImu2lMWwyCDZQkzXbPVAokzyHa8yitSNreLrvLcdtjd8YE/ZFM983NnB"
    "ckieJStU1is7ANcnsBAYk6tKHCNNmVCrIb2xKNsCIvR4LdZIbO2dHhClVINWfoxCvGhHF+"
    "YE7PxtiBwCurS8phc6yOGLguUlV1y8VZvbi5ucoI24tBXpo+XF/0mUz4OsuudCccaDrIRd"
    "QkvspqYUXgnm7EliHCXZZBd48Z5HKZPTuzqwL0h+QLLy/aLAA3V7V52qCyTejxN5HYl5Wy"
    "MYXaoFRMLKQGC0XtRd5RL7IuiNqJjl1+kyuxSe+Kztorx73jl2lmJ2/LVRtRIvfTJnRVO2"
    "nnnaM9tLvjofVDwhBKToYURPtpkw9GhcEE0E4PbXchj1e3wuPVLXq8Yh8LnkJCkK1WOCUD"
    "L+mhaVQR7TocNNr80OaH1lK1+bEvHVvcD3WWXaCYnpSD6QSlhBHJ1KyaopRLD2ksge/mKe"
    "VGSSZT6Y4N3LvB5f22irMYyQ8isiK3+x7iqEu13ZcEZ7TZtztm376ZLLUE6ZtgO2+ayPVv"
    "C8okqOtTJhueoWyr8tLwUgG3l2uCWowENt+IrcpUGZRi95RFkYUgmWoqnA5pkHY26LXPFC"
    "bmhlROtJW09C4NitRJoHtI4Cy3VXXYZVB7SJt2/e2Ehyhy/TWkRjxeWVFio6cWXSw30dPr"
    "O76/587As9EU2SFwDItviDNDGy+IThCzXzM75BQ30VGHa8u/YZa/Dwj0qKovNA3aQ8FPsN"
    "pOQnH7dtr469/3oy0L/9Q21mrbEoiaAYWy1PDqXYFSML2gwQobA+GQWGp7MqUgmvkVmA9d"
    "FxClgr4UpCVbtGxaoMwYMgkcQzbhq45sKVoP8uUHOeOEP46K4pEgWjLE82GahaI0FUGavO"
    "YxhtDmhppJmVxQkRYFYEsI3bTMeGdTsvL6qnf2JNuX8iqLvdwTls1k5V95GtOSYVl3Dm7i"
    "ElffIDNBrWGqWobYXZipoNhDWYX6OULTrjd505u86cjCzkQWdFLxznVsIam4MSHoZvk5FX"
    "zqOlVkAcIqsrHTw6hIonJG9mXuco0ddu+mZEu+L/kCkvnRuAYW93rTwTrD5LfYDx1AqtZS"
    "zzc5qAqb+1FjxdXUOz1jLBYt8qjz9g0InqFtWIiiP6BnxFcygpCMgcXOsN/pBBp+OHKQFQ"
    "XMHeDZrJsMn71lMby+1qsPvaH3+BiFG/4xFJPZsPP4aBD8EhiAQOMrAr9OxqkxehOX44uH"
    "2aHDDjw+EhifZrDf8OhvQw/aiDsY2c2hMXaQHxiIGhSzxqznQuCwhgHmx9hjTtEUBsY4pC"
    "G7mTUJiXdo9IwJsm32Puwphh6jmj0K+8cu4TLu2VXPGThgl+NeN55sxC44crD1HERPx3p8"
    "TsWYYNcYQfY8Q2/+rLbOO2hi3oGq/3Ult2uzlKJa/K7xB6LiN0xj2lm6X8PSoJGElNPY90"
    "K3MPNLwrmbHaidSNYWP/FOAKF9bvCfTLgygX9uCLHvRYBzIwXcemTGR56nXJY+B+mlArN0"
    "RvOqIp1zkKYzLxUINTGRVruWxrSyoL2spNn8pseNMufXUUOjfcE74TLUvuAd7diCL1jXcK"
    "3uzdz85jfN9cGV732zbS/cZ0hp9IYF71t86qDK6xZEjba4iqCixdxiY3mNSx6Ue3WmwAkl"
    "6l65WycBaL+O3K+TIlJhnGZRG3RFzK7d0LqTJ4JDX4XHBNCW4Vl3Xh0K+K4XBEpU1krPQg"
    "annQtftCGwB4ZA3DsjJR0ji2plPm/39HQR0X16Wi67+TmJhbAdPVeE8SVKbhzeL9dwefx8"
    "0Viy7SLvLxxgAMvCoUeNMSYiztkbGGy80BGmxi0mFDiSWLEKeujdgiB4wcSOQr8BZWaVzU"
    "OvI4u8+dSYgGACA2MYdo+OTwwPTtllfYf3NtPkdEC1iQFV6AKktIRbAmijNbM2CZNJn0YB"
    "G+Rvpuo2lXncfsvsTBSKyxHb9GfSRoVUCbStSngNUermr0CQpNA11BYEUyZJiep+qllUKz"
    "/0WsYjs++YcoOmqlv+ZXB6Zfk8p9Dne3cSIBmj79GagWqLW8dUd9Di1jHVHe3Y5fcMS2f7"
    "r7h1mGIJRHMCiJkvIr0g3PJcpNaeaycNs8UqV6SBO3x6t4Mf4SIR5QbVxNS6n1yKlBIf2Z"
    "yyak+Zme6lBTxmtwODtxaeLuFp47UHwLLYYM17vlhbidNM8QJDrw+sCYcYiFcqBNhColqC"
    "L3hoACNyv3k295+JwgX84hk+JC4KAi6PxDn46iOiV0RsrCNN1fuzktdn696JWtw+fFVg7r"
    "9RoTGNWYtdvVmH5NnJAjSenZSyyE8VSfQJHKNXVRrnqA26e9bm6jk+WyRPJa+KptJUzvJM"
    "OkCszL+UWZDH6qUxtrw0hpg+YbBEV2aRuiO33JEETvHzUt9kFqk7Ui9Wo30utTjTtrUkR7"
    "PyOpfPYt/sKhIN8jccLLiMRLL2xnbyenqQIGvSkXgtZmcOqjwWYN6mMVshltYiSr9JSQ3i"
    "rPe2mumxlhrEiiR1SALpIjnlVlUKos38lE9VKZl61rydBNayY2TpPgjl62SW74OwsaW0a5"
    "to17Ym5lbTRr/8H9HB1f4="
)
