from tortoise import BaseDBAsyncClient

RUN_IN_TRANSACTION = True

# NOTE: MODELS_STATE is intentionally omitted — it must be regenerated by
# running `aerich migrate` in an environment with a live database (it is a
# machine-generated snapshot, not hand-authorable). The upgrade DDL here is
# correct: it drops the local User/Session/UserAPIKey tables now that
# authentication is handled by Keycloak. `conversations.user_id` and
# `messages.user_id` keep their columns (and lose their FK via CASCADE) — they
# become plain UUID columns referencing the Keycloak subject id.


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        DROP TABLE IF EXISTS "user_api_keys" CASCADE;
        DROP TABLE IF EXISTS "sessions" CASCADE;
        DROP TABLE IF EXISTS "users" CASCADE;"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    # Irreversible: the dropped tables' data is gone. No-op.
    return ""
