"""initial

Revision ID: 0001
Revises:
Create Date: 2026-08-19 14:06:11.679350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pgroonga")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('connection_type', sa.Enum('MCP', 'API', 'A2A', name='connectiontype', native_enum=False, length=10), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'maintenance', 'disabled', name='agencystatus', native_enum=False, length=20), nullable=False),
    sa.Column('auto_maintenance', sa.Boolean(), nullable=False),
    sa.Column('stats_reset_at', sa.DateTime(), nullable=True),
    sa.Column('data_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('endpoint_url', sa.String(length=1000), nullable=True),
    sa.Column('auth_method', sa.String(length=50), nullable=True),
    sa.Column('auth_header', sa.String(length=100), nullable=True),
    sa.Column('base_path', sa.String(length=255), nullable=True),
    sa.Column('api_key_name', sa.String(length=100), nullable=True),
    sa.Column('request_format', sa.String(length=50), nullable=True),
    sa.Column('api_endpoints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('api_spec_raw', sa.Text(), nullable=True),
    sa.Column('expected_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('api_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('router_hint', sa.Text(), nullable=False),
    sa.Column('dispatch_timeout_s', sa.Integer(), nullable=True),
    sa.Column('mcp_tool_name', sa.String(length=255), nullable=True),
    sa.Column('conformance_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('rating_up', sa.Integer(), nullable=False),
    sa.Column('rating_down', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agencies'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('object_type', sa.String(length=30), nullable=True),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('preview', sa.Text(), nullable=True),
    sa.Column('agencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('response_time', sa.String(length=50), nullable=True),
    sa.Column('external_session_id', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_table('domain_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_events'))
    )
    op.create_table('executive_briefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executive_briefs'))
    )
    op.create_table('llm_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('auth_header', sa.String(length=100), nullable=False),
    sa.Column('auth_scheme', sa.String(length=50), nullable=False),
    sa.Column('timeout_seconds', sa.Float(), nullable=False),
    sa.Column('request_usage', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_rps', sa.Integer(), nullable=True),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.Column('max_queue_size', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_providers')),
    sa.UniqueConstraint('name', name=op.f('uq_llm_providers_name'))
    )
    op.create_table('llm_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('agency_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage'))
    )
    op.create_table('rate_limit_counters',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('window_start', sa.BigInteger(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_limit_counters')),
    sa.UniqueConstraint('key', 'window_start', name=op.f('uq_rate_limit_counters_key'))
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('group', sa.String(length=50), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('connection_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('connection_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('assistant_message_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_connection_logs_agency_id_agencies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connection_logs'))
    )
    op.create_table('golden_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('expected_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_golden_questions_agency_id_agencies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_golden_questions'))
    )
    op.create_table('llm_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('timeout_override', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['llm_providers.id'], name=op.f('fk_llm_routes_provider_id_llm_providers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_routes')),
    sa.UniqueConstraint('purpose', name=op.f('uq_llm_routes_purpose'))
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_references', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rating', sa.String(length=10), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('agency_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_table('popular_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_key', sa.String(length=500), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('seed', 'auto', 'manual', name='popularquestionsource', native_enum=False, length=10), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_popular_questions_agency_id_agencies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_popular_questions')),
    sa.UniqueConstraint('text_key', name=op.f('uq_popular_questions_text_key'))
    )
    op.create_table('eval_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('golden_question_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('judge_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['golden_question_id'], ['golden_questions.id'], name=op.f('fk_eval_results_golden_question_id_golden_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_results'))
    )
    # ### end Alembic commands ###
    op.execute("CREATE INDEX ix_messages_content_pgroonga ON messages USING pgroonga (content)")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_messages_content_pgroonga")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eval_results')
    op.drop_table('popular_questions')
    op.drop_table('messages')
    op.drop_table('llm_routes')
    op.drop_table('golden_questions')
    op.drop_table('connection_logs')
    op.drop_table('settings')
    op.drop_table('rate_limit_counters')
    op.drop_table('llm_usage')
    op.drop_table('llm_providers')
    op.drop_table('executive_briefs')
    op.drop_table('domain_events')
    op.drop_table('conversations')
    op.drop_table('audit_logs')
    op.drop_table('agencies')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS pgroonga")
