postgres_password: ENC[AES256_GCM,data:DCJap6pY1pbox71/A5i9NGZbuKcvwAzZNJBjom7m1ns=,iv:D+SGXA5WCl8Ed+5f/wrFJ2O1cVVOGPlX8qbXcVsDfkw=,tag:7wSVtcOaoipNQiCzqqdzzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d3war6th9w0y8p3xn9g4te4kn25ld6p5xvmpvxcfkkw0ac8aq5lsy0u2ym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aGVxL3VYYXg5R0ZhVUFK
            WmpMaE9YNFMwbUgzTytaVWYrUW9ndENmR1dzCmRvd3dpMTNtMmtObW54dUZFbmND
            OFNsSzBHNDRmbGVUQlVJMVQ2YVVTbWsKLS0tIFVNcVBxSWF4cUpjaTNnWEZ2L0xt
            ajlydENNa3AxcFM4bmQ2SXRxcnc3UHcKs67cyxiz10BxCAVWXRTxNmZzOkmMV8x0
            Nywyte2G5d9gPcNDmKTKkymkpyojIHsCPcedurZF1TUA1glKVOIiFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-17T16:50:43Z"
    mac: ENC[AES256_GCM,data:9K4/G6KfRri+mAzFCIWxwwLMQ0p71AOAzmI2RjAa0DFGnDqtFZxbUZr7kEjsy4qrNqdO8cdMGT+MDVa3nrYcZxP0c2Cu6EbjTyK7Ca1f0SQF2VbYdgHIkYvVfNzst1uzvw9v3CUe8Oh+a9eYpsAx9/jInQYQL7QCoB97dbWzHFM=,iv:itEps5xv7wSY2NuHT96WLSJunzWa9qs+ZRsoiKRIgzc=,tag:BHFidjbdCWM5Bf+bvLdH8w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
