postgres_password: ENC[AES256_GCM,data:jk7lLPTgBbFfW8zDQM4=,iv:r9QbWb/XaM3tISOL2JJRCgoE72ALyp0kpQgBtMVCaiU=,tag:ClnFkI9IgusgZBzqYmoxrA==,type:str]
openrouter_api_key: ENC[AES256_GCM,data:X3tefpEuP8DzdGIMWqzjcCf1mnGKPnPdiezqX9xz1u7vqI067JnzcjvkmnaRcKjPQlJcTP1fma+G6DC1FI1M3kD4o67Kp1cfTA==,iv:RFUIqN6t8z+6IACXMjJGbICLojbuTsyG8Nj93QotxYw=,tag:G2KJ5XKw2lDBaf6+U6xA7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d3war6th9w0y8p3xn9g4te4kn25ld6p5xvmpvxcfkkw0ac8aq5lsy0u2ym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aGVxL3VYYXg5R0ZhVUFK
            WmpMaE9YNFMwbUgzTytaVWYrUW9ndENmR1dzCmRvd3dpMTNtMmtObW54dUZFbmND
            OFNsSzBHNDRmbGVUQlVJMVQ2YVVTbWsKLS0tIFVNcVBxSWF4cUpjaTNnWEZ2L0xt
            ajlydENNa3AxcFM4bmQ2SXRxcnc3UHcKs67cyxiz10BxCAVWXRTxNmZzOkmMV8x0
            Nywyte2G5d9gPcNDmKTKkymkpyojIHsCPcedurZF1TUA1glKVOIiFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-17T17:02:26Z"
    mac: ENC[AES256_GCM,data:F7pWq9nsdzyqsgtzo0fOkxu5/DR6iamesXYDji+zfUt37qBiNt5fpyGY0RKJ+kImxKnbCWN1GXoumqnxBEkcHAg/tRs+o8qD2NLtB26p7erv192ScweJsrS75sXWbyS6TNDQ8APtoIQ2fohxTJkbUGyTPGa5tzznLs+WPViFxP0=,iv:OgHJ6kA7cGLFgBHl2mGjmn1nkWLmpaUp0rel+wEGsMI=,tag:9+pwYeSr6a6PYus7uLX0hg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
