postgres_password: ENC[AES256_GCM,data:DCJap6pY1pbox71/A5i9NGZbuKcvwAzZNJBjom7m1ns=,iv:D+SGXA5WCl8Ed+5f/wrFJ2O1cVVOGPlX8qbXcVsDfkw=,tag:7wSVtcOaoipNQiCzqqdzzQ==,type:str]
openrouter_api_key: ENC[AES256_GCM,data:ehedCEoXOF842INIj+Hgo6964ZyUcczjoSrQPuOXiEK+,iv:MRHWJfTVOmZSlIxJdubIz6uVzREan44f798KbvPqCB4=,tag:rVjktQmw9hm0hpmz/4Ep/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d3war6th9w0y8p3xn9g4te4kn25ld6p5xvmpvxcfkkw0ac8aq5lsy0u2ym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aGVxL3VYYXg5R0ZhVUFK
            WmpMaE9YNFMwbUgzTytaVWYrUW9ndENmR1dzCmRvd3dpMTNtMmtObW54dUZFbmND
            OFNsSzBHNDRmbGVUQlVJMVQ2YVVTbWsKLS0tIFVNcVBxSWF4cUpjaTNnWEZ2L0xt
            ajlydENNa3AxcFM4bmQ2SXRxcnc3UHcKs67cyxiz10BxCAVWXRTxNmZzOkmMV8x0
            Nywyte2G5d9gPcNDmKTKkymkpyojIHsCPcedurZF1TUA1glKVOIiFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-17T16:05:29Z"
    mac: ENC[AES256_GCM,data:h6NBSIhY6z50HVoA2urmLpp/geZ/IxYwy27T9wVjALGGXpg9qe9Sq8Bh6hY79Xi1IfSSJ/0BSm1UPM8528B8w91fUBzvMO5ylNNWMPf/c/7Zdbjin6difTCceMT3pjxWjKgBRsCKqr/Naw3SnilBilyGsT+9YTXggrs7D5lsWRM=,iv:CaHlgt+Fna6kep/+PjnopZfxgRZRSWXbDbIS8v7ZF4w=,tag:HaIEpUafwMgy+FRMrDJHNg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
