name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  release:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v')
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check required secrets
        run: |
          : "${OPENROUTER_API_KEY:?Secret OPENROUTER_API_KEY is not set}"
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

      - name: Write .env
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          {
            echo "ENV=production"
            echo "EXTERNAL_HTTP_PORT=80"
            echo "EXTERNAL_HTTPS_PORT=443"
            echo "EXTERNAL_POSTGRES_PORT=5432"
            echo "CERT_DOMAIN=chatbotportal.opdc.ai.in.th"
            echo "CERT_EMAIL=dogajack@gmail.com"
            echo "OPENROUTER_API_KEY=$OPENROUTER_API_KEY"
          } > .env

      - name: Build and deploy
        run: docker compose -f compose.yaml up -d --build --remove-orphans
